# Generated by Django 3.2 on 2021-04-09 07:15

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loss_communication', '0002_auto_20210404_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='is_dirty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loss_communication.farmer'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='tillage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loss_communication.tillage'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf'),
        ),
    ]
