# Generated by Django 3.2 on 2021-04-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loss_communication', '0003_auto_20210409_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
